// #TODO:TENGO QUE EMPEZAR A INCORPORAR LA FUNCONALIDAD CON EL TOKEN
// # TODO:TENGO QUE INCORPORAR EL LOG DE USUARIO //FRONT
// # TODO:TANTO EL LOGIN COMO EL LOG OUT //LOG OUT
// # TODO:TENGO QUE ICORPORAR DE SER POSIBLE EL AUTO PREDICT EN EL BUSCADOR
// # TODO: TENGO QUE VER DE INCORPORAR UNA PAGINACION DE SER POSIBLE
// # TODO:TENGO QUE VER DE INCORPORAR EL DARKMODE DE SER NECESARIO COMO UN EXTRA
// # TODO:TENGO QUE HACER EL README
